export const ClientEvent = {
  RoomCreate: "room:create",
  RoomJoin: "room:join",
  PlayerReady: "player:ready",
  ScenarioSelect: "scenario:select",
  DifficultySelect: "difficulty:select",
  GameStart: "game:start",
  SoloNextAction: "solo:nextAction",
  HeroMove: "hero:move",
  HeroMoveTo: "hero:moveTo",
  HeroLegalMoves: "hero:legalMoves",
  UseVortex: "hero:useVortex",
  TakeEscalator: "hero:takeEscalator",
  ExplorePlaceTile: "explore:placeTile",
  SandTimerActivate: "sandtimer:activate",
  SignalSend: "signal:send",
  DiscussionEnd: "discussion:end",
  SyncRequest: "sync:request",
  GamePlayAgain: "game:playAgain",
  GameReturnToLobby: "game:returnToLobby",
  DisableCamera: "barbarian:disableCamera",
  MageCrystalExplore: "mage:crystalExplore",
} as const;

export const ServerEvent = {
  RoomCreated: "room:created",
  RoomJoined: "room:joined",
  GameStarted: "game:started",
  HeroLegalMoves: "hero:legalMoves",
  StateUpdated: "state:updated",
  CommunicationUpdated: "communication:updated",
  TimerUpdated: "timer:updated",
  TilePlaced: "tile:placed",
  GameEffect: "game:effect",
  AlarmTriggered: "alarm:triggered",
  GameVictory: "game:victory",
  GameDefeat: "game:defeat",
  RoomReset: "room:reset",
  ActionAccepted: "action:accepted",
  ActionRejected: "action:rejected",
  SyncState: "sync:state",
  ServerError: "server:error",
  DiscussionStarted: "discussion:started",
  DiscussionEnded: "discussion:ended",
  SignalReceived: "signal:received",
  ObjectivesUpdated: "objectives:updated",
  AchievementsUnlocked: "achievements:unlocked",
  ActionCardsRotated: "actionCards:rotated",
  GuardMoved: "guard:moved",
  HeroCaught: "hero:caught",
} as const;
