export enum ClientEvent {
  RoomCreate = "room:create",
  RoomJoin = "room:join",
  GameStart = "game:start",
  SoloNextAction = "solo:nextAction",
  HeroMove = "hero:move",
  HeroMoveTo = "hero:moveTo",
  HeroLegalMoves = "hero:legalMoves",
  UseVortex = "hero:useVortex",
  TakeEscalator = "hero:takeEscalator",
  SandTimerActivate = "sandtimer:activate",
  SignalSend = "signal:send",
  DiscussionEnd = "discussion:end",
  SyncRequest = "sync:request",
  ExplorePlaceTile = "explore:placeTile",
  ScenarioSelect = "scenario:select",
  DifficultySelect = "difficulty:select",
  DisableCamera = "barbarian:disableCamera",
  MageCrystalExplore = "mage:crystalExplore",
  GamePlayAgain = "game:playAgain",
  GameReturnToLobby = "game:returnToLobby",
  PlayerReady = "player:ready",
}
