export enum ServerEvent {
  ServerError = "server:error",
  ActionAccepted = "action:accepted",
  ActionRejected = "action:rejected",
  RoomCreated = "room:created",
  RoomJoined = "room:joined",
  GameStarted = "game:started",
  HeroLegalMoves = "hero:legalMoves",
  StateUpdated = "state:updated",
  DiscussionStarted = "discussion:started",
  DiscussionEnded = "discussion:ended",
  SignalReceived = "signal:received",
  CommunicationUpdated = "communication:updated",
  TimerUpdated = "timer:updated",
  GameDefeat = "game:defeat",
  GameVictory = "game:victory",
  AlarmTriggered = "alarm:triggered",
  SyncState = "sync:state",
  TilePlaced = "tile:placed",
  ObjectivesUpdated = "objectives:updated",
  AchievementsUnlocked = "achievements:unlocked",
  GuardMoved = "guard:moved",
  HeroCaught = "hero:caught",
  GameEffect = "game:effect",
  RoomReset = "room:reset",
  ActionCardsRotated = "actionCards:rotated",
}
